/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { GlassCard } from "@/components/ui/GlassCard";
import { GlassButton } from "@/components/ui/GlassButton";
import { Download, Printer, FileText, Scale, CheckCircle, AlertTriangle, RefreshCw } from "lucide-react";

interface Step7Props {
  caseData: {
    id: string;
    title: string;
    category: string;
    description: string;
    location: string;
    jurisdiction: string;
    relevantDates: string;
    parties: string[];
    documents: Array<{ id: string; name: string; size: number; type: string; status: string }>;
    facts: {
      summary: string;
      keyClaims: string[];
      contradictions: string[];
      parties: string[];
      dates: string[];
      events: string[];
      evidence: string[];
    } | null;
    laws: Array<{ id: number; name: string; section: string; explanation: string; relevance: string }> | null;
    similarCases: Array<{ id: string; name: string; court: string; year: string; issue: string; relevance: string; source: string }> | null;
    analysis: {
      summary: string;
      keyFacts: string[];
      relevantLaws: string[];
      argumentsA: string[];
      argumentsB: string[];
      supportingEvidence: string[];
      similarCases: string[];
      legalIssues: string[];
      questions: string[];
    } | null;
  };
  onPrevious: () => void;
}

export default function Step7_FinalReport({ caseData, onPrevious }: Step7Props) {
  const handleDownload = () => {
    // Create a text report
    const report = `
FRIEND COURT AI - CASE ANALYSIS REPORT
========================================

Case ID: ${caseData.id}
Title: ${caseData.title}
Category: ${caseData.category}
Date: ${new Date().toLocaleDateString()}

CASE OVERVIEW
-------------
${caseData.description}

PARTIES INVOLVED
----------------
${caseData.parties.join(", ")}

KEY FACTS
---------
${caseData.facts?.keyClaims?.join("\n") || "Not available"}

RELEVANT LAWS
-------------
${caseData.laws?.map((l: { name: string; section: string }) => `${l.name} - ${l.section}`).join("\n") || "Not available"}

SIMILAR CASES
-------------
${caseData.similarCases?.map((c: { name: string; year: string }) => `${c.name} (${c.year})`).join("\n") || "Not available"}

AI ANALYSIS
-----------
${caseData.analysis?.summary || "Not available"}

ARGUMENTS FOR SIDE A
--------------------
${caseData.analysis?.argumentsA?.join("\n") || "Not available"}

ARGUMENTS FOR SIDE B
--------------------
${caseData.analysis?.argumentsB?.join("\n") || "Not available"}

SUPPORTING EVIDENCE
-------------------
${caseData.analysis?.supportingEvidence?.join("\n") || "None"}

LEGAL ISSUES
------------
${caseData.analysis?.legalIssues?.join("\n") || "None identified"}

DISCLAIMER
----------
This AI-generated information is for informational purposes only and does not constitute legal advice or a court decision. 
Verify important information with a qualified legal professional and authoritative legal sources.

Generated by Friend Court AI
    `.trim();

    // Create download
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `FriendCourt-Report-${caseData.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleStartNew = () => {
    localStorage.removeItem("currentAnalysis");
    window.location.href = "/analysis/new";
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-lg bg-accentGold/10 border border-accentGold/20 flex items-center justify-center">
          <FileText className="w-5 h-5 text-accentGold" />
        </div>
        <div>
          <h2 className="text-xl font-semibold text-white">Final Report</h2>
          <p className="text-sm text-textSecondary">Comprehensive case analysis report</p>
        </div>
      </div>

      {/* Report Header */}
      <GlassCard variant="highlight" className="p-8">
        <div className="text-center space-y-4">
          <div className="w-16 h-16 rounded-full bg-surface border border-glassBorder flex items-center justify-center mx-auto">
            <Scale className="w-8 h-8 text-accentGold" />
          </div>
          <h1 className="text-3xl font-bold text-white">Friend Court AI</h1>
          <p className="text-lg text-textSecondary">Case Analysis Report</p>
          <div className="flex items-center justify-center gap-6 text-sm text-textSecondary">
            <span>Case ID: {caseData.id}</span>
            <span>•</span>
            <span>{new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </GlassCard>

      {/* Report Content */}
      <div className="space-y-6">
        {/* Case Overview */}
        <GlassCard className="p-6">
          <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5 text-accentGold" />
            Case Overview
          </h3>
          <div className="space-y-4">
            <div>
              <span className="text-xs text-textSecondary uppercase tracking-wider">Title</span>
              <p className="text-white mt-1">{caseData.title}</p>
            </div>
            <div>
              <span className="text-xs text-textSecondary uppercase tracking-wider">Category</span>
              <p className="text-white mt-1">{caseData.category}</p>
            </div>
            <div>
              <span className="text-xs text-textSecondary uppercase tracking-wider">Description</span>
              <p className="text-white mt-1">{caseData.description}</p>
            </div>
            <div>
              <span className="text-xs text-textSecondary uppercase tracking-wider">Parties</span>
              <p className="text-white mt-1">{caseData.parties.join(", ")}</p>
            </div>
          </div>
        </GlassCard>

        {/* Extracted Facts */}
        {caseData.facts && (
          <GlassCard className="p-6">
            <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-accentGold" />
              Extracted Facts
            </h3>
            <div className="space-y-3">
              <div>
                <span className="text-xs text-textSecondary uppercase tracking-wider">Summary</span>
                <p className="text-white mt-1">{caseData.facts.summary}</p>
              </div>
              <div>
                <span className="text-xs text-textSecondary uppercase tracking-wider">Key Claims</span>
                <ul className="mt-2 space-y-2">
                  {caseData.facts.keyClaims?.map((claim: string, index: number) => (
                    <li key={index} className="text-sm text-white flex items-start gap-2">
                      <span className="text-accentGold">•</span>
                      {claim}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </GlassCard>
        )}

        {/* Relevant Laws */}
        {caseData.laws && caseData.laws.length > 0 && (
          <GlassCard className="p-6">
            <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Scale className="w-5 h-5 text-accentCyan" />
              Relevant Laws
            </h3>
            <div className="space-y-3">
              {caseData.laws.map((law: { id: number; name: string; section: string; explanation: string; relevance: string }) => (
                <div key={law.id} className="p-4 rounded-lg bg-surface border border-glassBorder">
                  <div className="flex items-start justify-between mb-2">
                    <h4 className="text-white font-medium">{law.name}</h4>
                    <span className="text-xs text-accentCyan">{law.section}</span>
                  </div>
                  <p className="text-sm text-textSecondary">{law.explanation}</p>
                </div>
              ))}
            </div>
          </GlassCard>
        )}

        {/* Similar Cases */}
        {caseData.similarCases && caseData.similarCases.length > 0 && (
          <GlassCard className="p-6">
            <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-accentGold" />
              Similar Cases
            </h3>
            <div className="space-y-3">
              {caseData.similarCases.map((caseItem: { id: string; name: string; court: string; year: string; issue: string; relevance: string; source: string }) => (
                <div key={caseItem.id} className="p-4 rounded-lg bg-surface border border-glassBorder">
                  <div className="flex items-start justify-between mb-2">
                    <h4 className="text-white font-medium">{caseItem.name}</h4>
                    <span className="text-xs text-textSecondary">{caseItem.year}</span>
                  </div>
                  <p className="text-sm text-textSecondary">{caseItem.relevance}</p>
                </div>
              ))}
            </div>
          </GlassCard>
        )}

        {/* AI Analysis */}
        {caseData.analysis && (
          <GlassCard variant="highlight" className="p-6">
            <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Scale className="w-5 h-5 text-accentGold" />
              AI Analysis
            </h3>
            <div className="space-y-4">
              <div>
                <span className="text-xs text-textSecondary uppercase tracking-wider">Summary</span>
                <p className="text-white mt-1">{caseData.analysis.summary}</p>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <span className="text-xs text-textSecondary uppercase tracking-wider">Arguments for Side A</span>
                  <ul className="mt-2 space-y-2">
                    {caseData.analysis.argumentsA?.map((arg: string, index: number) => (
                      <li key={index} className="text-sm text-white flex items-start gap-2">
                        <span className="text-accentGold">•</span>
                        {arg}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <span className="text-xs text-textSecondary uppercase tracking-wider">Arguments for Side B</span>
                  <ul className="mt-2 space-y-2">
                    {caseData.analysis.argumentsB?.map((arg: string, index: number) => (
                      <li key={index} className="text-sm text-white flex items-start gap-2">
                        <span className="text-accentCyan">•</span>
                        {arg}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {caseData.analysis.legalIssues && caseData.analysis.legalIssues.length > 0 && (
                <div className="p-4 rounded-lg bg-red-500/5 border border-red-500/20">
                  <div className="flex items-start gap-2">
                    <AlertTriangle className="w-4 h-4 text-red-400 mt-0.5" />
                    <div>
                      <span className="text-xs text-red-400 uppercase tracking-wider">Legal Issues</span>
                      <ul className="mt-2 space-y-1">
                        {caseData.analysis.legalIssues.map((issue: string, index: number) => (
                          <li key={index} className="text-sm text-red-300">• {issue}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </GlassCard>
        )}

        {/* Disclaimer */}
        <GlassCard variant="secondary" className="p-6">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-accentGold mt-0.5" />
            <div>
              <h3 className="text-sm font-semibold text-white mb-2">Important Disclaimer</h3>
              <p className="text-xs text-textSecondary leading-relaxed">
                This AI-generated information is for informational purposes only and does not constitute legal advice or a court decision. 
                Verify important information with a qualified legal professional and authoritative legal sources. 
                The analysis provided is based on the information submitted and may not reflect all relevant facts or legal considerations.
              </p>
            </div>
          </div>
        </GlassCard>
      </div>

      {/* Actions */}
      <div className="flex flex-col sm:flex-row justify-between gap-4 pt-6 border-t border-glassBorderSecondary">
        <GlassButton variant="secondary" onClick={onPrevious} className="px-6">
          Previous
        </GlassButton>
        <div className="flex gap-4">
          <GlassButton variant="secondary" onClick={handleDownload} className="px-6">
            <Download className="w-4 h-4" />
            Download Report
          </GlassButton>
          <GlassButton variant="secondary" onClick={handlePrint} className="px-6">
            <Printer className="w-4 h-4" />
            Print
          </GlassButton>
          <GlassButton variant="primary" onClick={handleStartNew} className="px-6">
            <RefreshCw className="w-4 h-4" />
            Start New Analysis
          </GlassButton>
        </div>
      </div>
    </div>
  );
}
